// Generated client for API group ai\n// TODO: Implement or import a common HTTP request wrapper function (e.g., fetchWrapper)\n/*\nasync function fetchWrapper(method, endpoint, params, needAuth) {\n  const SiyuanKernelPrefix = typeof window === 'object' ? '' : 'http://127.0.0.1:6806';\n  const url = SiyuanKernelPrefix + endpoint;\n  const options = { method, headers: {} };\n  if (method === 'POST' && params && Object.keys(params).length > 0) { // Only add body if params exist and are not empty\n    options.headers['Content-Type'] = 'application/json';\n    options.body = JSON.stringify(params);\n  }\n  if (needAuth) {\n    // Example: Retrieve and add auth token\n    // const token = localStorage.getItem('siyuan-auth-token'); \n    // if (token) options.headers['Authorization'] = `Token ${token}`;\n    options.headers['Authorization'] = 'Bearer YOUR_TOKEN_HERE'; // Placeholder\n  }\n  const response = await fetch(url, options);\n  if (!response.ok) {\n    let errorData = 'Failed to parse error response';\n    try { errorData = await response.json(); } catch (e) { try {errorData = await response.text(); } catch (e2) { /* ignore secondary error */ }}\n    console.error('API Error:', response.status, errorData); \n    throw new Error(`API Error ${response.status}: ${JSON.stringify(errorData)}`);\n  }\n  const contentType = response.headers.get('content-type');\n  if (contentType && contentType.includes('application/json')) {\n    return response.json();\n  } \n  return response.text(); // Or handle other content types\n}\n*/\n\n/**\n * 与 ChatGPT 进行简单对话。\n * (Requires authentication, Requires admin role)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.msg 发送给 ChatGPT 的消息内容
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 返回消息
 * @property {any} Data ChatGPT 的回复内容
 */\nexport async function chatGPT(params) {\n  // Example: return fetchWrapper('POST', '/api/ai/chatGPT', params, true);\n  console.log('Mock call to chatGPT with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<ChatGPTResponse>\n}\n\n/**\n * 调用 ChatGPT 对指定的块ID列表执行特定动作。\n * (Requires authentication, Requires admin role)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {Array<string>} params.ids 要操作的块 ID 列表
 * @param {string} params.action 要执行的动作指令
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 返回消息
 * @property {any} Data ChatGPT 执行动作后的返回结果
 */\nexport async function chatGPTWithAction(params) {\n  // Example: return fetchWrapper('POST', '/api/ai/chatGPTWithAction', params, true);\n  console.log('Mock call to chatGPTWithAction with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<ChatGPTWithActionResponse>\n}\n\n