// Generated client for API group archive\n// TODO: Implement or import a common HTTP request wrapper function (e.g., fetchWrapper)\n/*\nasync function fetchWrapper(method, endpoint, params, needAuth) {\n  const SiyuanKernelPrefix = typeof window === 'object' ? '' : 'http://127.0.0.1:6806';\n  const url = SiyuanKernelPrefix + endpoint;\n  const options = { method, headers: {} };\n  if (method === 'POST' && params && Object.keys(params).length > 0) { // Only add body if params exist and are not empty\n    options.headers['Content-Type'] = 'application/json';\n    options.body = JSON.stringify(params);\n  }\n  if (needAuth) {\n    // Example: Retrieve and add auth token\n    // const token = localStorage.getItem('siyuan-auth-token'); \n    // if (token) options.headers['Authorization'] = `Token ${token}`;\n    options.headers['Authorization'] = 'Bearer YOUR_TOKEN_HERE'; // Placeholder\n  }\n  const response = await fetch(url, options);\n  if (!response.ok) {\n    let errorData = 'Failed to parse error response';\n    try { errorData = await response.json(); } catch (e) { try {errorData = await response.text(); } catch (e2) { /* ignore secondary error */ }}\n    console.error('API Error:', response.status, errorData); \n    throw new Error(`API Error ${response.status}: ${JSON.stringify(errorData)}`);\n  }\n  const contentType = response.headers.get('content-type');\n  if (contentType && contentType.includes('application/json')) {\n    return response.json();\n  } \n  return response.text(); // Or handle other content types\n}\n*/\n\n/**\n * 将指定的 .zip 文件解压到指定路径。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.zipPath 要解压的 .zip 文件的绝对路径或相对于工作空间的路径
 * @param {string} params.path 解压到目标目录的绝对路径或相对于工作空间的路径
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 返回消息
 * @property {any} Data Data
 */\nexport async function unzip(params) {\n  // Example: return fetchWrapper('POST', '/api/archive/unzip', params, true);\n  console.log('Mock call to unzip with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<UnzipResponse>\n}\n\n/**\n * 将指定路径的文件或目录压缩到指定的 .zip 文件。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.path 要压缩的文件或目录的绝对路径或相对于工作空间的路径
 * @param {string} params.zipPath 生成的 .zip 文件保存的绝对路径或相对于工作空间的路径
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 返回消息
 * @property {any} Data Data
 */\nexport async function zip(params) {\n  // Example: return fetchWrapper('POST', '/api/archive/zip', params, true);\n  console.log('Mock call to zip with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<ZipResponse>\n}\n\n