// Generated client for API group bookmark\n// TODO: Implement or import a common HTTP request wrapper function (e.g., fetchWrapper)\n/*\nasync function fetchWrapper(method, endpoint, params, needAuth) {\n  const SiyuanKernelPrefix = typeof window === 'object' ? '' : 'http://127.0.0.1:6806';\n  const url = SiyuanKernelPrefix + endpoint;\n  const options = { method, headers: {} };\n  if (method === 'POST' && params && Object.keys(params).length > 0) { // Only add body if params exist and are not empty\n    options.headers['Content-Type'] = 'application/json';\n    options.body = JSON.stringify(params);\n  }\n  if (needAuth) {\n    // Example: Retrieve and add auth token\n    // const token = localStorage.getItem('siyuan-auth-token'); \n    // if (token) options.headers['Authorization'] = `Token ${token}`;\n    options.headers['Authorization'] = 'Bearer YOUR_TOKEN_HERE'; // Placeholder\n  }\n  const response = await fetch(url, options);\n  if (!response.ok) {\n    let errorData = 'Failed to parse error response';\n    try { errorData = await response.json(); } catch (e) { try {errorData = await response.text(); } catch (e2) { /* ignore secondary error */ }}\n    console.error('API Error:', response.status, errorData); \n    throw new Error(`API Error ${response.status}: ${JSON.stringify(errorData)}`);\n  }\n  const contentType = response.headers.get('content-type');\n  if (contentType && contentType.includes('application/json')) {\n    return response.json();\n  } \n  return response.text(); // Or handle other content types\n}\n*/\n\n/**\n * 构建并返回当前工作空间的所有书签列表。书签是为块设置的特定名称，方便快速访问。\n * (Requires authentication)\n * @returns {Promise<object>}\n * @property {number} Code API 调用返回码，0 表示成功
 * @property {string} Msg API 调用返回消息
 * @property {Array<object>} Data 书签数据数组，每个元素是一个书签分组及其包含的书签块列表
 */\nexport async function getBookmark() {\n  // Example: return fetchWrapper('POST', '/api/bookmark/getBookmark', undefined, true);\n  console.log('Mock call to getBookmark with:', "'no params'");\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<GetBookmarkResponse>\n}\n\n/**\n * 根据书签名称（即块的 IAL 中 bookmark 属性的值）移除一个或多个书签。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.bookmark 要移除的书签的名称 (块 IAL 中 bookmark 属性的值)
 * @property {number} Code API 调用返回码，0 表示成功，其他表示失败
 * @property {string} Msg API 调用返回消息
 * @property {object} Data? Data
 */\nexport async function removeBookmark(params) {\n  // Example: return fetchWrapper('POST', '/api/bookmark/removeBookmark', params, true);\n  console.log('Mock call to removeBookmark with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<RemoveBookmarkResponse>\n}\n\n/**\n * 将具有特定旧书签名称（块 IAL 中 bookmark 属性的旧值）的所有书签重命名为一个新的书签名称。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.oldBookmark 要重命名的旧书签名称 (块 IAL 中 bookmark 属性的当前值)
 * @param {string} params.newBookmark 新的书签名称 (将写入块 IAL 中 bookmark 属性的新值)
 * @property {number} Code API 调用返回码，0 表示成功，其他表示失败
 * @property {string} Msg API 调用返回消息
 * @property {object} Data? Data
 */\nexport async function renameBookmark(params) {\n  // Example: return fetchWrapper('POST', '/api/bookmark/renameBookmark', params, true);\n  console.log('Mock call to renameBookmark with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<RenameBookmarkResponse>\n}\n\n