// Generated client for API group lute\n// TODO: Implement or import a common HTTP request wrapper function (e.g., fetchWrapper)\n/*\nasync function fetchWrapper(method, endpoint, params, needAuth) {\n  const SiyuanKernelPrefix = typeof window === 'object' ? '' : 'http://127.0.0.1:6806';\n  const url = SiyuanKernelPrefix + endpoint;\n  const options = { method, headers: {} };\n  if (method === 'POST' && params && Object.keys(params).length > 0) { // Only add body if params exist and are not empty\n    options.headers['Content-Type'] = 'application/json';\n    options.body = JSON.stringify(params);\n  }\n  if (needAuth) {\n    // Example: Retrieve and add auth token\n    // const token = localStorage.getItem('siyuan-auth-token'); \n    // if (token) options.headers['Authorization'] = `Token ${token}`;\n    options.headers['Authorization'] = 'Bearer YOUR_TOKEN_HERE'; // Placeholder\n  }\n  const response = await fetch(url, options);\n  if (!response.ok) {\n    let errorData = 'Failed to parse error response';\n    try { errorData = await response.json(); } catch (e) { try {errorData = await response.text(); } catch (e2) { /* ignore secondary error */ }}\n    console.error('API Error:', response.status, errorData); \n    throw new Error(`API Error ${response.status}: ${JSON.stringify(errorData)}`);\n  }\n  const contentType = response.headers.get('content-type');\n  if (contentType && contentType.includes('application/json')) {\n    return response.json();\n  } \n  return response.text(); // Or handle other content types\n}\n*/\n\n/**\n * 将指定ID的块内容导出为标准 Markdown 格式的字符串。\n * (Requires authentication)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.id 要导出内容的块的ID
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 错误信息，成功时为空字符串
 * @property {string} Data 导出的标准 Markdown 内容
 */\nexport async function copyStdMarkdown(params) {\n  // Example: return fetchWrapper('POST', '/api/lute/copyStdMarkdown', params, true);\n  console.log('Mock call to copyStdMarkdown with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<CopyStdMarkdownResponse>\n}\n\n/**\n * 将输入的 HTML 字符串转换为思源笔记的块级 DOM 结构 (仍为HTML字符串，但经过Lute处理)。会处理本地资源路径、空列表项、单列表格转段落等情况。\n * (Requires authentication)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.dom 要转换的 HTML 字符串
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 错误信息，成功时为空字符串
 * @property {string} Data 转换后的块级 DOM (HTML 格式的字符串)
 */\nexport async function html2BlockDOM(params) {\n  // Example: return fetchWrapper('POST', '/api/lute/html2BlockDOM', params, true);\n  console.log('Mock call to html2BlockDOM with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<Html2BlockDOMResponse>\n}\n\n/**\n * 对传入的块级 DOM 字符串执行 Lute 引擎的 SpinBlockDOM 处理，进行原生渲染相关的优化。\n * (Requires authentication)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.dom 要处理的块级 DOM 字符串 (HTML 格式)
 * @property {number} Code 返回码，0 表示成功
 * @property {string} Msg 错误信息，成功时为空字符串
 * @property {object} Data Data
 */\nexport async function spinBlockDOM(params) {\n  // Example: return fetchWrapper('POST', '/api/lute/spinBlockDOM', params, true);\n  console.log('Mock call to spinBlockDOM with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<SpinBlockDOMResponse>\n}\n\n