// Generated client for API group template\n// TODO: Implement or import a common HTTP request wrapper function (e.g., fetchWrapper)\n/*\nasync function fetchWrapper(method, endpoint, params, needAuth) {\n  const SiyuanKernelPrefix = typeof window === 'object' ? '' : 'http://127.0.0.1:6806';\n  const url = SiyuanKernelPrefix + endpoint;\n  const options = { method, headers: {} };\n  if (method === 'POST' && params && Object.keys(params).length > 0) { // Only add body if params exist and are not empty\n    options.headers['Content-Type'] = 'application/json';\n    options.body = JSON.stringify(params);\n  }\n  if (needAuth) {\n    // Example: Retrieve and add auth token\n    // const token = localStorage.getItem('siyuan-auth-token'); \n    // if (token) options.headers['Authorization'] = `Token ${token}`;\n    options.headers['Authorization'] = 'Bearer YOUR_TOKEN_HERE'; // Placeholder\n  }\n  const response = await fetch(url, options);\n  if (!response.ok) {\n    let errorData = 'Failed to parse error response';\n    try { errorData = await response.json(); } catch (e) { try {errorData = await response.text(); } catch (e2) { /* ignore secondary error */ }}\n    console.error('API Error:', response.status, errorData); \n    throw new Error(`API Error ${response.status}: ${JSON.stringify(errorData)}`);\n  }\n  const contentType = response.headers.get('content-type');\n  if (contentType && contentType.includes('application/json')) {\n    return response.json();\n  } \n  return response.text(); // Or handle other content types\n}\n*/\n\n/**\n * 将指定 ID 的文档内容保存为一个模板。可以指定模板名称，以及是否覆盖同名模板。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.id 要作为模板保存的文档ID。
 * @param {string} params.name 模板的名称。
 * @param {boolean} params.overwrite 如果已存在同名模板，是否覆盖。
 * @property {number} code 错误码，0 表示成功，其他表示失败。
 * @property {string} msg 错误或成功信息。
 * @property {null} data 成功时总是为 null。
 */\nexport async function docSaveAsTemplate(params) {\n  // Example: return fetchWrapper('POST', '/api/template/docSaveAsTemplate', params, true);\n  console.log('Mock call to docSaveAsTemplate with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<DocSaveAsTemplateResponse>\n}\n\n/**\n * 根据给定的模板文件路径和可选的上下文块ID，渲染模板内容。可以指定是否为预览模式。\n * (Requires authentication, Requires admin role, Unavailable in read-only mode)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.path 模板文件的绝对路径。
 * @param {string} params.id 可选的上下文块ID，用于模板内获取该块的信息。
 * @param {boolean} [params.preview] preview
 * @property {number} code 错误码，0 表示成功。
 * @property {string} msg 错误信息。
 * @property {object} data data
 */\nexport async function renderTemplate(params) {\n  // Example: return fetchWrapper('POST', '/api/template/render', params, true);\n  console.log('Mock call to renderTemplate with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<RenderTemplateResponse>\n}\n\n/**\n * 使用 Go 的 Sprig 模板函数库渲染给定的模板字符串。\n * (Requires authentication)\n * @param {object} params - Request parameters.\n * @returns {Promise<object>}\n * @param {string} params.template 包含 Sprig 模板语法的字符串。
 * @property {number} code 错误码，0 表示成功。
 * @property {string} msg 错误信息。
 * @property {string} data data
 */\nexport async function renderSprig(params) {\n  // Example: return fetchWrapper('POST', '/api/template/renderSprig', params, true);\n  console.log('Mock call to renderSprig with:', params);\n  return Promise.resolve({}); // TODO: Ensure mock response matches Promise<RenderSprigResponse>\n}\n\n