export const blockApiDefs = [
  {
    method: "POST",
    endpoint: "/api/block/appendBlock",
    en: "appendBlock",
    zh_cn: "插入后置子块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/appendDailyNoteBlock",
    en: "appendDailyNoteBlock",
    zh_cn: "追加日记块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/batchUpdateBlock",
    en: "batchUpdateBlock",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/checkBlockExist",
    en: "checkBlockExist",
    zh_cn: "检查块是否存在",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/checkBlockFold",
    en: "checkBlockFold",
    zh_cn: "检查块是否折叠",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/checkBlockRef",
    en: "checkBlockRef",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/deleteBlock",
    en: "deleteBlock",
    zh_cn: "删除块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/foldBlock",
    en: "foldBlock",
    zh_cn: "折叠块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockBreadcrumb",
    en: "getBlockBreadcrumb",
    zh_cn: "获取块面包屑",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockDOM",
    en: "getBlockDOM",
    zh_cn: "获取块DOM",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockDefIDsByRefText",
    en: "getBlockDefIDsByRefText",
    zh_cn: "根据引用文本获取块定义id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockIndex",
    en: "getBlockIndex",
    zh_cn: "获取块索引",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockInfo",
    en: "getBlockInfo",
    zh_cn: "获取块信息",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockKramdown",
    en: "getBlockKramdown",
    zh_cn: "获取块kramdown",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockSiblingID",
    en: "getBlockSiblingID",
    zh_cn: "获取块同级id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlockTreeInfos",
    en: "getBlockTreeInfos",
    zh_cn: "获取块树信息",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlocksIndexes",
    en: "getBlocksIndexes",
    zh_cn: "获取块索引",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getBlocksWordCount",
    en: "getBlocksWordCount",
    zh_cn: "获取块字数",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getChildBlocks",
    en: "getChildBlocks",
    zh_cn: "获取子块",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getContentWordCount",
    en: "getContentWordCount",
    zh_cn: "获取内容字数",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getDOMText",
    en: "getDOMText",
    zh_cn: "获取DOM文本",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getDocInfo",
    en: "getDocInfo",
    zh_cn: "获取文档信息",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getDocsInfo",
    en: "getDocsInfo",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getHeadingChildrenDOM",
    en: "getHeadingChildrenDOM",
    zh_cn: "获取标题子块DOM",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getHeadingChildrenIDs",
    en: "getHeadingChildrenIDs",
    zh_cn: "获取标题子块id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getHeadingDeleteTransaction",
    en: "getHeadingDeleteTransaction",
    zh_cn: "获取标题删除事务",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getHeadingLevelTransaction",
    en: "getHeadingLevelTransaction",
    zh_cn: "获取标题级别事务",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getRecentUpdatedBlocks",
    en: "getRecentUpdatedBlocks",
    zh_cn: "获取最近更新的块",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getRefIDs",
    en: "getRefIDs",
    zh_cn: "获取引用id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getRefIDsByFileAnnotationID",
    en: "getRefIDsByFileAnnotationID",
    zh_cn: "根据文件标注id获取引用id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getRefText",
    en: "getRefText",
    zh_cn: "获取引用文本",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getTailChildBlocks",
    en: "getTailChildBlocks",
    zh_cn: "获取尾部子块",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getTreeStat",
    en: "getTreeStat",
    zh_cn: "获取树状态",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/getUnfoldedParentID",
    en: "getUnfoldedParentID",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/insertBlock",
    en: "insertBlock",
    zh_cn: "插入块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/moveBlock",
    en: "moveBlock",
    zh_cn: "移动块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/moveOutlineHeading",
    en: "moveOutlineHeading",
    zh_cn: "移动大纲标题",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/prependBlock",
    en: "prependBlock",
    zh_cn: "插入前置子块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/prependDailyNoteBlock",
    en: "prependDailyNoteBlock",
    zh_cn: "插入日记块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/setBlockReminder",
    en: "setBlockReminder",
    zh_cn: "设置块提醒",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/swapBlockRef",
    en: "swapBlockRef",
    zh_cn: "交换块引用",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/transferBlockRef",
    en: "transferBlockRef",
    zh_cn: "转移块引用",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/unfoldBlock",
    en: "unfoldBlock",
    zh_cn: "展开块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/block/updateBlock",
    en: "updateBlock",
    zh_cn: "更新块",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  }
];
