export const filetreeApiDefs = [
  {
    method: "POST",
    endpoint: "/api/filetree/changeSort",
    en: "changeSort",
    zh_cn: "更改排序",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/createDailyNote",
    en: "createDailyNote",
    zh_cn: "创建日记",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/createDoc",
    en: "createDoc",
    zh_cn: "创建文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/createDocWithMd",
    en: "createDocWithMd",
    zh_cn: "创建文档-md",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/doc2Heading",
    en: "doc2Heading",
    zh_cn: "文档转换为标题",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/duplicateDoc",
    en: "duplicateDoc",
    zh_cn: "复制文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getDoc",
    en: "getDoc",
    zh_cn: "获取文档",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getDocCreateSavePath",
    en: "getDocCreateSavePath",
    zh_cn: "获取文档创建路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getFullHPathByID",
    en: "getFullHPathByID",
    zh_cn: "根据id获取完整层级路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getHPathByID",
    en: "getHPathByID",
    zh_cn: "通过id获取层级路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getHPathByPath",
    en: "getHPathByPath",
    zh_cn: "通过路径获取层级路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getHPathsByPaths",
    en: "getHPathsByPaths",
    zh_cn: "批量通过路径获取层级路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getIDsByHPath",
    en: "getIDsByHPath",
    zh_cn: "根据层级路径获取id",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getPathByID",
    en: "getPathByID",
    zh_cn: "根据id获取路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/getRefCreateSavePath",
    en: "getRefCreateSavePath",
    zh_cn: "获取块引创建路径",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/heading2Doc",
    en: "heading2Doc",
    zh_cn: "标题转换为文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/li2Doc",
    en: "li2Doc",
    zh_cn: "列表转换为文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/listDocTree",
    en: "listDocTree",
    zh_cn: "树形列出 doc",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/listDocsByPath",
    en: "listDocsByPath",
    zh_cn: "获取路径下文档列表",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/moveDocs",
    en: "moveDocs",
    zh_cn: "批量移动文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/moveDocsByID",
    en: "moveDocsByID",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/moveLocalShorthands",
    en: "moveLocalShorthands",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/refreshFiletree",
    en: "refreshFiletree",
    zh_cn: "刷新文档树",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/removeDoc",
    en: "removeDoc",
    zh_cn: "移除文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/removeDocByID",
    en: "removeDocByID",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/removeDocs",
    en: "removeDocs",
    zh_cn: "批量删除文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/removeIndexes",
    en: "removeIndexes",
    zh_cn: "删除索引",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/renameDoc",
    en: "renameDoc",
    zh_cn: "重命名文档",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/renameDocByID",
    en: "renameDocByID",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/searchDocs",
    en: "searchDocs",
    zh_cn: "搜索文档",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/filetree/upsertIndexes",
    en: "upsertIndexes",
    zh_cn: "创建/更新索引",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  }
];
