export const systemApiDefs = [
  {
    method: "POST",
    endpoint: "/api/system/addMicrosoftDefenderExclusion",
    en: "addMicrosoftDefenderExclusion",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "GET",
    endpoint: "/api/system/bootProgress",
    en: "bootProgress",
    zh_cn: "获取启动进度",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/bootProgress",
    en: "bootProgress",
    zh_cn: "获取启动进度",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/checkUpdate",
    en: "checkUpdate",
    zh_cn: "检查更新",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/checkWorkspaceDir",
    en: "checkWorkspaceDir",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/createWorkspaceDir",
    en: "createWorkspaceDir",
    zh_cn: "创建工作空间",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/currentTime",
    en: "currentTime",
    zh_cn: "获取当前时间",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/exit",
    en: "exit",
    zh_cn: "退出",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/exportConf",
    en: "exportConf",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/exportLog",
    en: "exportLog",
    zh_cn: "导出日志",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "GET",
    endpoint: "/api/system/getCaptcha",
    en: "GetCaptcha",
    zh_cn: "获取验证码",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getChangelog",
    en: "getChangelog",
    zh_cn: "获取更新日志",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getConf",
    en: "getConf",
    zh_cn: "获取配置",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getEmojiConf",
    en: "getEmojiConf",
    zh_cn: "获取emoji配置",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getMobileWorkspaces",
    en: "getMobileWorkspaces",
    zh_cn: "获取移动端工作空间目录",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getNetwork",
    en: "getNetwork",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getSysFonts",
    en: "getSysFonts",
    zh_cn: "获取系统字体",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getWorkspaceInfo",
    en: "getWorkspaceInfo",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/getWorkspaces",
    en: "getWorkspaces",
    zh_cn: "获取工作空间目录",
    needAuth: true,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/ignoreAddMicrosoftDefenderExclusion",
    en: "ignoreAddMicrosoftDefenderExclusion",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/importConf",
    en: "importConf",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/loginAuth",
    en: "LoginAuth",
    zh_cn: "登录鉴权",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/logoutAuth",
    en: "LogoutAuth",
    zh_cn: "退出登录",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/reloadUI",
    en: "reloadUI",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/removeWorkspaceDir",
    en: "removeWorkspaceDir",
    zh_cn: "移除动作空间",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/removeWorkspaceDirPhysically",
    en: "removeWorkspaceDirPhysically",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setAPIToken",
    en: "setAPIToken",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setAccessAuthCode",
    en: "setAccessAuthCode",
    zh_cn: "设置鉴权码",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setAppearanceMode",
    en: "setAppearanceMode",
    zh_cn: "设置外观模式",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setAutoLaunch",
    en: "setAutoLaunch",
    zh_cn: "设置自动启动",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setDownloadInstallPkg",
    en: "setDownloadInstallPkg",
    zh_cn: "设置是否下载安装包",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setFollowSystemLockScreen",
    en: "setFollowSystemLockScreen",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zh_cn: undefined,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setGoogleAnalytics",
    en: "setGoogleAnalytics",
    zh_cn: "设置谷歌数据分析",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setNetworkProxy",
    en: "setNetworkProxy",
    zh_cn: "设置网络代理",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setNetworkServe",
    en: "setNetworkServe",
    zh_cn: "设置网络服务器",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setUILayout",
    en: "setUILayout",
    zh_cn: "设置UI布局",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/setWorkspaceDir",
    en: "setWorkspaceDir",
    zh_cn: "设置工作空间目录",
    needAuth: true,
    needAdminRole: true,
    unavailableIfReadonly: true,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/uiproc",
    en: "addUIProcess",
    zh_cn: "UI生成进度",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "GET",
    endpoint: "/api/system/version",
    en: "version",
    zh_cn: "获取软件版本",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  },
  {
    method: "POST",
    endpoint: "/api/system/version",
    en: "version",
    zh_cn: "获取软件版本",
    needAuth: false,
    needAdminRole: false,
    unavailableIfReadonly: false,
    zodRequestSchema: (z) => ({}),
    zodResponseSchema: (z) => ({})
  }
];
